name: Publish in DockerHub

on:  
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Run tests
        run: mvn test
      - name: Generate Docker image
        run: mvn spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=${{ secrets.DOCKERHUB_USERNAME }}/items:v1
      - name: Login to DockerHub
        run: docker login -u "${{ secrets.raulrodriguezlr }}" -p "${{ secrets.eba7b4fd-48a7-46bb-987a-62fbb09f69b6 }}" 
      - name: Push image to DockerHub
        run: docker push ${{ secrets.raulrodriguezlr }}/items:v1
